# Site
name: "Epitech Lyon Innovation Hub"
title: "Epitech-Lyon"
description: "scientific talks, workshops, hub projects"
logo: 'assets/images/epitech-logo-signature-noir.png'
favicon: 'assets/images/epitech-logo-signature-noir.png'
baseurl: ''
google_analytics: 'UA-178278290-1'
disqus: 'p4tth3c4t'
mailchimp-list: 'https://github.us2.list-manage.com/subscribe?u=183f5527b6f815b09e0c6fcfe&id=5e645fad9e'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  kanmeugne:
    name: Patrick S. Kanmeugne
    display_name: Patrick S. Kanmeugne
    email: patrick.simokanmeugne@epitech.eu
    web: https://kanmeugne.github.io
    avatar: 'assets/images/avatars/kanmeugne.jpg'
    twitter: https://twitter.com/patricksimok
    description: "IA (distruted) Scientist. Scientific blogger, multi agents system enthousiast."
  jhouvenaghel:
    name: Juliette Houvenaghel
    display_name: Juliette H.
    avatar: 'assets/images/avatars/jhouvenaghel.jpg'
    email: juliette.houvenaghel@epitech.eu
    web: https://www.epitech.eu
    twitter: https://twitter.com/jhouvenaghel
    description: "Juliette H. est une étudiante en 4e année à Epitech (Lyon). Elle est passionnée par le Web, le design et le développement mobile."
  ymagnin:
    name: Yann Magnin
    display_name: Yann M.
    avatar: 'assets/images/avatars/ymagnin.jpg'
    email: yann.magnin@epitech.eu
    web: https://www.epitech.eu
    twitter: https://twitter.com/ymagnin
    description: "Yann M. est étudiant en 4e année à Epitech (Lyon). Il est passionné de Hardware, programmation bas niveau et"
  nmary:
    name: Nicolas Mary
    display_name: Nicolas M.
    avatar: 'assets/images/avatars/nmary.jpg'
    email: nicolas.mary@epitech.eu
    web: https://www.epitech.eu
    twitter: https://twitter.com/nmary
    description: "Nicolas M. est en 2e année à Epitech (Lyon). Il est passionné par le design et la programmation de jeux vidéos "
  hbach:
      name: Hugo Bach
      display_name: Hugo B.
      avatar: 'assets/images/avatars/hbach.jpg'
      email: hugo.bach@epitech.eu
      web: https://www.epitech.eu
      twitter: https://twitter.com/hbach
      description: "Hugo B. est en 3e année à Epitech (Lyon). Il est passionné de cybersécurité, back-end et devops"
  llhuile:
    name: Leo Lhuile
    display_name: Leo L.
    avatar: 'assets/images/avatars/llhuile.jpg'
    email: leo.lhuile@epitech.eu
    web: https://www.epitech.eu
    twitter: https://twitter.com/llhuile
    description: "Leo L. est en 4e année à Epitech (Lyon). Il est passionné par la programmation des jeux video et le développement Web "
  pcoulon:
    name: Pierre Coulon
    display_name: Pierre C.
    avatar: 'assets/images/avatars/pcoulon.jpg'
    email: pierre.coulon@epitech.eu
    web: https://www.epitech.eu
    twitter: https://twitter.com/pcoulon
    description: "P. Coulon est en 4e année à Epitech (Lyon). Il est passionné par la programmation web et les objects connectés"
  tpoisson:
    name: Tristan Poisson
    display_name: Tristan P.
    avatar: 'assets/images/avatars/tpoisson.jpg'
    email: tristan.poisson@epitech.eu
    web: https://www.epitech.eu
    twitter: https://twitter.com/tpoisson
    description: "Tristan P. est en 3e année à Epitech (Lyon). Il est passionné par la programmation mobile et les objects connectés"
  mverdier:
    name: Maugan Verdier
    display_name: Maugan V.
    avatar: 'assets/images/avatars/mverdier.jpg'
    email: maugan.verdier@epitech.eu
    web: https://www.epitech.eu
    twitter: https://twitter.com/mverdier
    description: "Maugan V. est en 3e année à Epitech (Lyon). Il est passionné par le hardware et la programmation bas niveau"
  mbelleville:
    name: Matheo Belleville
    display_name: Matheo B.
    avatar: 'assets/images/avatars/mbelleville.jpg'
    email: matheo.belleville@epitech.eu
    web: https://www.epitech.eu
    twitter: https://twitter.com/mbelleville
    description: "Matheo B. est en 3e année à Epitech (Lyon). Il est passionné par le jeu video et la programmation sous unity"  
  mhechaichi:
    name: Moussa Hechaichi
    display_name: Moussa H.
    avatar: 'assets/images/avatars/mhechaichi.jpg'
    email: moussa.hechaichi@epitech.eu
    web: https://www.epitech.eu
    twitter: https://twitter.com/mheichaichi
    description: "Moussa Hechaichi est en 4e année à Epitech (Lyon). Il est passionné par le web et la programmation mobile"
  mbarbet:
    name: Max Barbet
    display_name: Max B.
    avatar: 'assets/images/avatars/mbarbet.jpg'
    email: max.barbet@epitech.eu
    web: https://www.epitech.eu
    twitter: https://twitter.com/mbarbet
    description: "M. Barbet est en 3e année à Epitech (Lyon). Il est passionné d'IA et de programation Web"
  jharrau:
    name: Jeremy Harrau
    display_name: Jeremy H.
    avatar: 'assets/images/avatars/jharrau.jpg'
    email: jeremy.harrau@epitech.eu
    web: https://www.epitech.eu
    twitter: https://twitter.com/jharrau
    description: "Jeremy Harrau est en 4e année à Epitech (Lyon). Il est passionné de Web design et de programmation mobile"
  eloiseau:
    name: Evan Loiseau
    display_name: Evan L.
    avatar: 'assets/images/avatars/eloiseau.jpg'
    email: evan.loiseau@epitech.eu
    web: https://www.epitech.eu
    twitter: https://twitter.com/eloiseau
    description: "Evan L. est en 3e année à Epitech (Lyon). Il est passionné de programmation de jeux video"
  troustan:
    name: Thomas Roustan
    display_name: Thomas R.
    avatar: 'assets/images/avatars/troustan.jpg'
    email: thomas.roustan@epitech.eu
    web: https://www.epitech.eu
    twitter: https://twitter.com/troustan
    description: "Thomas R. est un étudiant en 3e année à Epitech (Lyon). Il est passionné de programmation de jeux video sous Unity et de Multimedia"  
  csaunier:
    name: Clément Saunier
    display_name: Clément S.
    avatar: 'assets/images/avatars/csaunier.jpg'
    email: clement.saunier@epitech.eu
    web: https://www.epitech.eu
    twitter: https://twitter.com/csaunier
    description: "Clément Saunier est un étudiant en 3e année à Epitech (Lyon). Il est passionné de programmation de jeux video sous Unity et de programmation mobile"
  meynard-longuet:
    name: Matthieu Eynard-Longuet
    display_name: Matthieu E.-L.
    avatar: 'assets/images/avatars/meynard-longuet.jpg'
    email: matthieu.eynard-longuet@epitech.eu
    web: https://www.epitech.eu
    twitter: https://twitter.com/meynard-longuet
    description: "Matthieu Eynard Longuet est un étudiant en 5e année à Epitech (Lyon). Il est passionné dela 3D et la VR/AR"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
